### Summary

# This module grabs an image from the screen and funnels
# it to the processing module

# -------------------------------------------------

from discord.ext import commands, tasks
from typing import List
from enum import Enum
import json


class DataGrabber(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.first_time = True
        self.last_state = 0

    @tasks.loop(seconds=1)
    async def grab_data(self):
        """grabs data from among.js, generated by a c# application scrapping the among us exe"""
        with open(r"F:\Desktop\Projetos\AmongUs\among.json") as data:
            js = json.load(data)
            if self.last_state != js['state']:
                if js['state'] == 0:  # LOBBY
                    await self.bot.unmute_and_clear()
                elif js['state'] == 1:  # TASKS
                    self.process_players(js)
                    await self.bot.mute()
                elif js['state'] == 2:  # DISCUSSION
                    self.process_players(js)
                    await self.bot.unmute()
                if self.last_state == 0:  # After the lobby, set players colors
                    await self.bot.set_colors(js)
                self.last_state = js['state']

    def process_players(self, js):
        for player in js['players']:
            if player['dead'] or player['disconnected']:
                self.bot.kill(player['name'])


if __name__ == "__main__":
    print("Please run start.py: ")
    exit()
